In [1]:
import numpy as np
import tensorflow as tf

In [2]:
A = tf.placeholder(tf.float32,shape=(None,3))
B = A+5
with tf. Session() as sess:
    B_val_1 = B.eval(feed_dict={A:[[1,2,3]]})
    B_val_2 = B.eval(feed_dict={A:[[5,6,7],[3,78,4]]})

In [3]:
print (B_val_1)
print (B_val_2)

[[ 6.  7.  8.]]
[[ 10.  11.  12.]
 [  8.  83.   9.]]
